worker_processes 1;
error_log /var/log/nginx/error.log info;

events {
    worker_connections 512;
}

http {
    # All defaults — no hardening
    # large_client_header_buffers 4 8k;    (default)
    # http2_max_concurrent_streams 128;    (default)
    # send_timeout 60s;                    (default)

    server {
        listen 443 ssl http2;

        ssl_certificate     /etc/nginx/server.crt;
        ssl_certificate_key /etc/nginx/server.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        root /srv;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
